spring:
  datasource:
    username: root
    password: srikanthaddanki123
    url: jdbc:mysql://localhost:3306/product
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect:  org.hibernate.dialect.MYSQL5Dialect  